import { verifyKey } from 'discord-interactions';
import { handleCommand } from './bot/commands/index.js';
// @ts-ignore - This is generated by Astro during build
import { handle as astroHandler } from '@astrojs/cloudflare/handler'; 

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    console.log("Incoming URL:", request.url); // Log this to see if it's malformed

    // 1. Route Discord Interactions (POST requests with signature headers)
    const signature = request.headers.get('x-signature-ed25519');
    const timestamp = request.headers.get('x-signature-timestamp');

    if (request.method === 'POST' && signature && timestamp) {
      const body = await request.text();
      const isValidRequest = await verifyKey(body, signature, timestamp, env.DISCORD_PUBLIC_KEY);
      
      if (!isValidRequest) {
        return new Response('Bad request signature', { status: 401 });
      }

      const interaction = JSON.parse(body);
      if (interaction.type === 1) return new Response(JSON.stringify({ type: 1 }));
      if (interaction.type === 2) return await handleCommand(interaction, env);
    }

    // 2. Route Everything Else to the Astro Website
    // This replaces the "Website integration requires..." message
    return astroHandler(request, env, ctx);
  }
};